export const UPDATESUTENDSNUMBER = 'UPDATESUTENDSNUMBER'
export const INCREAMENTSTUDENTSNUMBER = 'INCREAMENTSTUDENTSNUMBER'
export const ARABIC = 'arabic'
export const ENGLISH = 'english'
export const FULLSCREEN = "full_screen"
export const UNFULLSCREEN = "un_full_screen"
export const ADMINLOGUNG = 'admin_loginn'
export const ADMINLOGUNGOUT = 'admin_logout'
export const CHANGE_GRADE = 'change_grade'

// MANAGE TEACHER STATES
export const CHANGE_CURRENT_PAGE = 'change_current_page'
export const TEACHERS = 'teachers'
export const TOTAL_PAGES = 'total_pages'
export const TEACHER_SECTION = 'teacher_section'
export const TEACHER_SOURCE = 'teachers_data_source'
export const ALL_TEACHER = 'all_teacher'
export const SEARCHING_TEACHER = 'searching_teacher'
export const SEARCH_INPUT_TEACHER = 'search_input_teacher'
export const TEACHER_COUNT = 'teachers_number'

// SHOWING TEACHER STATES 
export const CHANGE_CURRENT_PAGE_DETAILS = 'change_current_page_details'
export const NUMBER_ROWS_DETAILS = 'number_rows_details'
export const SEARCHING_TEACHER_DETAILS = 'searching_teacher_details'
export const TEACHERS_DETAILS = 'teachers_details'
export const TOTAL_PAGES_DETAILS = 'total_pages_details'
export const TEACHER_SOURCE_DETAILS = 'teachers_data_source_details'
export const TEACHER_COUNT_DETAILS = 'teachers_number_details'

// STUDENT BILLS SATATES
export const M_FILTER_STUDENTS_BY_CLASS = 'm_filter_students_by_class'
export const M_SEARCH_FILED = 'm_search_filed'
export const M_STUDENT_BILLS_BALANCE = 'm_student_bills_balance'
export const M_BILL_CURRENT_PAGE = 'm_bill_current_page'
export const M_BILL_TOTAL_PAGES = 'm_bill_total_page'
export const M_DATA_ORIGIN = 'm_origin_data'
export const ALL_STUDENTS_BILLS = 'all_students_bills'
export const SEARCHING_STUDENTS_BILLS = 'filtering_students_bills'
export const S_FILTER_STUDENTS_BY_CLASS = 's_filter_students_by_class'
export const S_SEARCH_FILED = 's_search_filed'
export const S_STUDENT_BILLS_BALANCE = 's_student_bills_balance'
export const S_BILL_CURRENT_PAGE = 's_bill_current_page'
export const S_BILL_TOTAL_PAGES = 's_bill_total_page'
export const S_DATA_ORIGIN = 's_origin_data'

// TEACHER BILLS SATETES
export const TEACHER_BILLS = 'teacher_bills'
export const TEACHER_BILLS_CURRENT_PAGE = 'teacher_bills_current_page'
export const TEACHER_BILLS_TOTAL_PAGE = 'teacher_bills_total_page'
export const TEACHER_BILLS_SEARCH_FIELD = 'teacher_bills_search_field'
export const TEACHER_BILLS_DATA_ORIGIN = 'teacher_bills_data_origin'
export const S_TEACHER_BILLS = 's_teacher_bills'
export const S_TEACHER_BILLS_CURRENT_PAGE = 's_teacher_bills_current_page'
export const S_TEACHER_BILLS_TOTAL_PAGE = 's_teacher_bills_total_page'
export const S_TEACHER_BILLS_SEARCH_FIELD = 's_teacher_bills_search_field'
export const S_TEACHER_BILLS_DATA_ORIGIN = 's_teacher_bills_data_origin'

// EXTERNAL BILLS STATE
export const M_EXTERNAL_BILLS_INCOME = 'm_external_bills_income'
export const M_EXTERNAL_BILLS_OUTCOME = 'm_external_bills_outcome'
export const M_EXTERNAL_BILLS_SEARCH_FIELD = 'm_external_bills_search_field'
export const M_EXTERNAL_BILLS_CURRENT_PAGE_IN = 'm_external_bills_current_page_in'
export const M_EXTERNAL_BILLS_CURRENT_PAGE_OUT = 'm_external_bills_current_page_out'
export const M_EXTERNAL_BILLS_TOTAL_PAGES_IN = 'm_external_bills_total_pages_in'
export const M_EXTERNAL_BILLS_TOTAL_PAGES_OUT = 'm_external_bills_total_pages_out'
export const M_EXTERNAL_BILLS_INCOME_ORIGIN = 'm_external_bills_income_origin'
export const M_EXTERNAL_BILLS_OUTCOME_ORIGIN = 'm_external_bills_outcome_origin'
export const M_ALL_EXTERNAL_RADIO_BUTTONS = 'm_all_external_radio_buttons'
export const M_ALL_EXTERNAL_SEARCH_BUTTON = 'm_all_external_search_button'
export const ALL_EXTERNAL_BILLS = 'all_external_bills'
export const EXTERNAL_SEARCHING_BILLS = 'external_searching_bills'
export const EXTERNAL_BILLS_INCOME = 'external_bills_income'
export const EXTERNAL_BILLS_OUTCOME = 'external_bills_outcome'
export const EXTERNAL_BILLS_SEARCH_FIELD = 'external_bills_search_field'
export const EXTERNAL_BILLS_CURRENT_PAGE_IN = 'external_bills_current_page_in'
export const EXTERNAL_BILLS_CURRENT_PAGE_OUT = 'external_bills_current_page_out'
export const EXTERNAL_BILLS_TOTAL_PAGES_IN = 'external_bills_total_pages_in'
export const EXTERNAL_BILLS_TOTAL_PAGES_OUT = 'external_bills_total_pages_out'
export const EXTERNAL_BILLS_INCOME_ORIGIN = 'external_bills_income_origin'
export const EXTERNAL_BILLS_OUTCOME_ORIGIN = 'external_bills_outcome_origin'
export const ALL_EXTERNAL_RADIO_BUTTONS = 'all_external_radio_buttons'
export const ALL_EXTERNAL_SEARCH_BUTTON = 'all_external_search_button'


export const SEARCH_INPUT_CLASS = 'search_input_class'
export const CHANGE_CLASS_PAGE = 'change_class_page'
export const MANAGE_CLASS_PAGE = 'manage_class_page'
export const SHOW_CLASS_PAGE = 'show_class_page'
export const CLASS_SECTION = 'class_teacher'



